name: Build, test and coverage

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
    - name: Build
      run: go build -v ./...
#    - name: Run coverage
#      run: go test -race -coverprofile=coverage.txt -covermode=atomic
#    - name: Upload coverage to Codecov
#      run: bash <(curl -s https://codecov.io/bash)
    - uses: actions/checkout@master
    - uses: codecov/codecov-action@v2